name: IncidenceStructures
version: "0.1"
date: 2019-08-27
description: |
    GAP implementation of abstract point-line incidence structures

authors:
    - name: Gábor P. Nagy
      url: https://algebra.math.bme.hu/nagy-gabor

maintainers:
    - name: Gábor P. Nagy
      url: https://algebra.math.bme.hu/nagy-gabor

GAP: ">= 4.9"

www: https://nagygp.github.io/IncidenceStructures/
readme: README.md
packageinfo: https://nagygp.github.io/IncidenceStructures/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/nagygp/IncidenceStructures/releases/download/v0.1/IncidenceStructures-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Nag19</span>]   <b class='BibAuthor'>Nagy, G. P.</b>,
     <i class='BibTitle'>IncidenceStructures, GAP implementation of abstract point-line incidence structures,
             Version 0.1</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://nagygp.github.io/IncidenceStructures/">https://nagygp.github.io/IncidenceStructures/</a></span>.
    </p>
    

bibtex: |
    @misc{ IncidenceStructures0.1,
      author =           {Nagy, G. P.},
      title =            {{IncidenceStructures}, GAP implementation of abstract point-line incidence structures, {V}ersion 0.1},
      month =            {Aug},
      year =             {2019},
      note =             {GAP package},
      howpublished =     {\href   {https://nagygp.github.io/IncidenceStructures/}  {\texttt{https://nagygp.github.io/}\discretionary
                          {}{}{}\texttt{IncidenceStructures/}}},
      printedkey =       {Nag19}
    }

