name: IncidenceStructures
version: "0.2"
date: 2019-09-01
description: |
    GAP implementation of abstract incidence structures

authors:
    - name: Gábor P. Nagy
      url: https://algebra.math.bme.hu/nagy-gabor

maintainers:
    - name: Gábor P. Nagy
      url: https://algebra.math.bme.hu/nagy-gabor

GAP: ">= 4.9"

needed-pkgs:
    - name: "BlissInterface"
      version: ">=0.2"
      url: "https://nagygp.github.io/BlissInterface/"

www: https://nagygp.github.io/IncidenceStructures/
readme: README.md
packageinfo: https://nagygp.github.io/IncidenceStructures/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/nagygp/IncidenceStructures/releases/download/v0.2/IncidenceStructures-0.2.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    incidence, incidence structure, design, Steiner system, finite geometry.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Nag19</span>]   <b class='BibAuthor'>Nagy, G. P.</b>,
     <i class='BibTitle'>IncidenceStructures, GAP implementation of abstract incidence structures,
             Version 0.2</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://nagygp.github.io/IncidenceStructures/">https://nagygp.github.io/IncidenceStructures/</a></span>.
    </p>
    

bibtex: |
    @misc{ IncidenceStructures0.2,
      author =           {Nagy, G. P.},
      title =            {{IncidenceStructures},  GAP implementation of abstract
                          incidence structures, {V}ersion 0.2},
      month =            {Sep},
      year =             {2019},
      note =             {GAP package},
      howpublished =     {\href  {https://nagygp.github.io/IncidenceStructures/}
                          {\texttt{https://nagygp.github.io/}\discretionary
                          {}{}{}\texttt{IncidenceStructures/}}},
      keywords =         {incidence;   incidence   structure;   design;  Steiner
                          system; finite geometry},
      printedkey =       {Nag19}
    }

