name: CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  # The CI test job
  test:
    name: ${{ matrix.gap-branch }} ${{ matrix.ABI }}
    runs-on: ubuntu-latest
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout glabella
        uses: actions/checkout@v2
        with:
          repository: nagygp/glabella
          path: glabella
      - uses: gap-actions/setup-gap-for-packages@v1
      - name: "Install glabella"
        run:  | 
          cd glabella
          ls -l
          ./autogen.sh
          ./configure --with-gaproot=/home/runner/gap
          make
          ln -f -s /home/runner/work/IncidenceStructures/IncidenceStructures/glabella gaproot/pkg/
          cd ..
        shell: bash
      - uses: gap-actions/run-test-for-packages@v1

