name: CI

on:
  push:
    branches:
      - master # change this to 'main' if necessary!
  pull_request:

jobs:
  # The CI test job
  test:
    name: CI test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup GAP for packages
        uses: gap-actions/setup-gap-for-packages@v1
        with: 
          GAP_PKGS_TO_CLONE: nagygp/glabella
          GAP_PKGS_TO_BUILD: "io profiling glabella"
          GAPBRANCH: stable-4.11
      - uses: gap-actions/run-test-for-packages@v1

